language: node_js
node_js: 
  - "5"
  - "6"
  - "7"
  - "9"
services:
  - mongodb
install:
  - travis_retry npm install
  - travis_retry npm install mocha
  - travis_retry npm install chai
  - travis_retry npm install mongoose
  - travis_retry npm install --only=dev
